### ISSUE TITLE
blabla

### ISSUE THREAD

**Issue by blackcrack** [XhmikosR/notepad2-mod#199] opened 2017-07-31 02:52 UTC
sorry

**Comment by franzalex** [comment] 2017-08-05 11:25
Turnover on the project may be slow but there is no way it can be classified as _"no more developed and maintained"_.

There is an equally long list of issues in Notepad3, including [a major one](https://github.com/rizonesoft/Notepad3/issues/34) I raised more than a month ago which has not received any acknowledgement yet. Both projects can be considered largely feature-complete save for a few bugs that need to be fixed.
   
Unless you are ready to contribute to either of the projects, I think you should cease and desist from this behaviour.

**Comment by blackcrack** [comment] 2017-08-06 00:16
blubb, why do you think do XhmikosR say nothing any more and give no support any more ?
since year when he did no answering any more !
If you're too lazy for reading behind, you lead others into the wrong..

https://github.com/XhmikosR/notepad2-mod/issues/143
https://github.com/XhmikosR/notepad2-mod/issues/144

https://github.com/XhmikosR/notepad2-mod/issues/148
https://github.com/XhmikosR/notepad2-mod/pull/172
https://github.com/XhmikosR/notepad2-mod/pull/179
https://github.com/XhmikosR/notepad2-mod/issues/191

@XhmikosR should ma by say by self what's going on ? :)
best regards
Blacky

**Comment by franzalex** [comment] 2017-08-06 01:22
In fact, as of the time of writing this post, the last commit (06f5999) is just about a day old and it is pull request #182 which fixes issue #37.  
Note that this is a clearly reproducible error which has been fixed in a well-documented pull request. Contrast this with #179 which was [closed](179#event-1018172857) by the owner or #172 which ended with some [abusive language](172#issuecomment-262678440).

My therefore point is, until @XhmikosR or any of the other contributors post that this project has been discontinued, or stops accepting well-documented pull requests, this project cannot be described as "_no more developed and maintained_". If, though, for one reason or the other, you feel like this project doesn't suit your needs, please move on to your preferred fork and stop littering this repo as @XhmikosR [asked you to](36#issuecomment-320423690).

**Comment by blackcrack** [comment] 2017-08-06 05:19
upps.. oky...

**Comment by blackcrack** [comment] 2017-08-06 12:23
https://www.essential-freebies.de/board/viewtopic.php?f=11&t=6507&p=141180#p141180

**Closed** 2017-08-06 12:23 UTC

**Comment by franzalex** [comment] 2017-08-06 17:10
That anyone reading this thread in future may know what was truly discussed before **blackcrack** vandalised his posts, I post here the original messages based on entries from the email notifications I received for this thread.

-----

[blackcrack@20170731T0252Z](https://github.com/XhmikosR/notepad2-mod/issues/199#issue-246631951)

> notepad2-mod it is no more developed and maintained ..  
please go to notepad3, because
>
> https://github.com/rizonesoft/Notepad3
>
> it is maintained and developing
>
> best regards
> Blacky

**Source:** [blackcrack@20170731T0252Z.eml](https://github.com/XhmikosR/notepad2-mod/files/1203260/blackcrack.20170731T0252Z.eml.txt)


------

[blackcrack@20170806T0016Z](https://github.com/XhmikosR/notepad2-mod/issues/199#issuecomment-320477722)

> blubb, why do you think do XhmikosR say nothing any more and give no support any more ?  
> since year when he did no answering any more !  
> If you're too lazy for reading behind, you lead others into the wrong..
> 
> #143
> #144
> 
> #148
> #172
> #179
> #191
>
> @xhmikosr should ma by say by self what's going on ? :)
> best regards
> Blacky

**Source:** [blackcrack@20170806T0016Z.eml](https://github.com/XhmikosR/notepad2-mod/files/1203262/blackcrack.20170806T0016Z.eml.txt)

**Comment by blackcrack** [comment] 2017-08-06 18:08
hey Alex Essilfie,

 you're a grudge? You are resentful ?
should i be it also ?

hey if i do a mistake and i clouse the issue, should you also stop it, because i have see, i have do a fail, but if you want start a War in the net ? huhh.. all the other see what for a Carackter you have..

soooooo, you mailserver have the ip 10.176.71.70 ..  gmailaccound .. humm franzalex
oookeyyy....

**Comment by franzalex** [comment] 2017-08-06 18:44
No, I have no grudge against you. Neither am I resentful. It is up to you though to decide how you want to react.

The objective of my action was solely to allow anyone coming across this later to know what was discussed since you decided, for reasons best known to you, to alter your initial messages in such a way that the rest of the conversation did not make sense any more. My intention is not to start '_a War in the net_' [sic].

**PS:** Besides refreshing the IP addresses every few hours, my ISP masks the true IP addresses of their clients so you'll not have any reliable way of knowing it unless I explicitly provide it. In short:  

> Do not even bother using the IP in the EML files posted.

**Comment by XhmikosR** [comment] 2017-08-06 20:33
Please, guys, there's no gain in continuing this discussion.

@blackcrack: you should NOT have done what you did, editing your posts. And even you shouldn't have made the issue in the first place. You could have asked me via email. It's at least unethical what you did.

I'm just one person. And besides, the main reason I made this, was because back in 2009 Kai Liu didn't maintain his patches any more. So, lack of knowledge (I never claimed to be a C developer), work and personal life don't allow me to spend almost any time on this project. That is why I have asked for help years ago. No serious proposition so far.

**Comment by franzalex** [comment] 2017-08-06 20:59
Thank you, @XhmikosR for your moderation on this issue.

### EDIT

In order to forestall such an occurrence in future, could you please consider putting the following in the [readme](https://github.com/XhmikosR/notepad2-mod/blob/master/Readme.md)?  

 1. That this repo is in maintenance mode (along with a clear description of what is meant by that)
 2. Exactly what kind of issues you (and other contributors) are inclined to work on.
 3. The exact nature of pull requests that you will consider merging into this repo.

Thank you.  
franzalex

**Comment by XhmikosR** [comment] 2017-08-07 07:59
I'm not even sure at this point what I want to merge and what not.

In the past I kept the `notepad2` branch with upstream code and master with custom one. If notepad is updated upstream, it would be a pain in the ass to merge now.

So anyway, the project just needs some people willing to take care of maintenance and who know what open source is meaning nothing should go in without discussing/reviewing it with the others.
